[book]
title = "balance.tf"
authors = ["TristenMilk", "rrredface"]
description = "A record of ideas for making Team Fortress 2 more interesting and less frustrating to play."
src = "src"

[build]
build-dir = "docs"

[output.html]
additional-css = ["css/custom.css"]
additional-js = ["custom.js"]
